table DimCarrera
	column CarreraKey
		dataType: string
		sourceColumn: CarreraKey

	column Carrera
		dataType: string
		sourceColumn: Carrera

	column TieneMeta
		dataType: boolean
		sourceColumn: TieneMeta

	partition DimCarrera = m
		mode: import
		source =
				let
				    Combined = Table.Combine({Table.SelectColumns(FactB26,{"CarreraKey"}),Table.SelectColumns(FactB25,{"CarreraKey"}),Table.SelectColumns(FactMetasCarrera,{"CarreraKey"})}),
				    Clean = Table.SelectRows(Combined,each [CarreraKey]<>null and [CarreraKey]<>""),
				    DistinctRows = Table.Distinct(Clean),
				    AddName = Table.AddColumn(DistinctRows,"Carrera",each [CarreraKey],type text),
				    AddTarget = Table.AddColumn(AddName,"TieneMeta",each List.Contains(FactMetasCarrera[CarreraKey],[CarreraKey]),type logical)
				in
				    AddTarget
