table DimCarreraMatriz
	lineageTag: 7d9f5c5b-8b52-4c76-b31a-202609290001

	column CarreraSGA
		dataType: string
		isKey
		lineageTag: 7d9f5c5b-8b52-4c76-b31a-202609290002
		sourceColumn: CarreraSGA

	column CarreraVisual
		dataType: string
		lineageTag: 7d9f5c5b-8b52-4c76-b31a-202609290003
		sourceColumn: CarreraVisual

	column TipoPrograma
		dataType: string
		lineageTag: 7d9f5c5b-8b52-4c76-b31a-202609290004
		sourceColumn: TipoPrograma

	column TipoCarrera
		dataType: string
		lineageTag: 7d9f5c5b-8b52-4c76-b31a-202609290005
		sourceColumn: TipoCarrera

	partition DimCarreraMatriz = m
		mode: import
		source =
				let
				    Catalog0 = FxLoadCarreraCatalog(),
				    Catalog = Table.SelectColumns(Catalog0,{"CarreraSGA","CarreraVisual","CarreraVisualNorm"},MissingField.Error),
				    Metas0 = FxLoadMetas(),
				    MetaCarreras0 = Table.Distinct(Table.SelectColumns(Metas0,{"Carrera"},MissingField.Error)),
				    MetaCarreras1 = Table.RenameColumns(MetaCarreras0,{{"Carrera","CarreraVisual"}}),
				    MetaCarreras = Table.AddColumn(MetaCarreras1,"CarreraVisualNorm",each FxNormalizeName([CarreraVisual]),type text),
				    MetaSolo = Table.NestedJoin(MetaCarreras,{"CarreraVisualNorm"},Catalog,{"CarreraVisualNorm"},"Cat",JoinKind.LeftAnti),
				    MetaConSGA = Table.AddColumn(MetaSolo,"CarreraSGA",each FxNormalizeName([CarreraVisual]),type text),
				    MetaCols = Table.SelectColumns(MetaConSGA,{"CarreraSGA","CarreraVisual","CarreraVisualNorm"},MissingField.Error),
				    Union = Table.Combine({Catalog,MetaCols}),
				    Base0 = Table.Distinct(Union,{"CarreraSGA"}),
				    Base = Table.TransformColumns(Base0,{{"CarreraSGA", each if _ = "PEDAGOGIA DE LA ACTIVIDAD FISICA Y DEL DEPORTE" then "PEDAGOGIA DE LA ACTIVIDAD FISICA Y DEPORTE" else _, type text}}),
				    AddTipoPrograma = Table.AddColumn(Base,"TipoPrograma",each FxTipoPrograma([CarreraVisual]),type text),
				    AddTipoCarrera = Table.AddColumn(AddTipoPrograma,"TipoCarrera",each FxTipoCarrera([CarreraVisual]),type text),
				    R = Table.Sort(Table.SelectColumns(AddTipoCarrera,{"CarreraSGA","CarreraVisual","TipoPrograma","TipoCarrera"},MissingField.Error),{{"CarreraVisual",Order.Ascending}})
				in
				    R

