table DimDiaPeriodo
	lineageTag: d9481616-1a18-40de-ac03-ff07c6919831

	column DiaPeriodo
		dataType: int64
		lineageTag: 72aa5ca3-666f-4e68-a21d-d5c258e04148
		summarizeBy: none
		sourceColumn: DiaPeriodo

	column FechaB26
		dataType: dateTime
		formatString: dd-MMM
		lineageTag: b667ba17-964e-4ace-9b88-6994bd652df3
		summarizeBy: none
		sourceColumn: FechaB26

		annotation UnderlyingDateTimeDataType = Date

	column EtiquetaDia
		dataType: string
		lineageTag: e751e46b-81d9-482f-9b25-7fa731f88039
		summarizeBy: none
		sourceColumn: EtiquetaDia
		sortByColumn: DiaPeriodo

	partition DimDiaPeriodo = m
		mode: import
		source =
				let
				    InicioB26 = #date(2026,5,1),
				    T = Table.FromList({1..260}, Splitter.SplitByNothing(), {"DiaPeriodo"}, null, ExtraValues.Error),
				    Types = Table.TransformColumnTypes(T, {{"DiaPeriodo", Int64.Type}}),
				    AddFecha = Table.AddColumn(Types, "FechaB26", each Date.AddDays(InicioB26, [DiaPeriodo]-1), type date),
				    AddEtiqueta = Table.AddColumn(AddFecha, "EtiquetaDia", each Date.ToText([FechaB26], "dd-MMM", "es-ES"), type text)
				in
				    AddEtiqueta

