table DimDiaPeriodo
	column DiaPeriodo
		dataType: int64
		summarizeBy: none
		sourceColumn: DiaPeriodo

	column FechaB26
		dataType: dateTime
		formatString: dd-MMM
		summarizeBy: none
		sourceColumn: FechaB26

	column EtiquetaDia
		dataType: string
		summarizeBy: none
		sourceColumn: EtiquetaDia
		sortByColumn: DiaPeriodo

	partition DimDiaPeriodo = m
		mode: import
		source =
				let
				    InicioB26 = #date(2026,5,1),
				    T = Table.FromList({1..260}, Splitter.SplitByNothing(), {"DiaPeriodo"}, null, ExtraValues.Error),
				    Types = Table.TransformColumnTypes(T, {{"DiaPeriodo", Int64.Type}}),
				    AddFecha = Table.AddColumn(Types, "FechaB26", each Date.AddDays(InicioB26, [DiaPeriodo]-1), type date),
				    AddEtiqueta = Table.AddColumn(AddFecha, "EtiquetaDia", each Date.ToText([FechaB26], "dd-MMM", "es-ES"), type text)
				in
				    AddEtiqueta
