table DimDiaPeriodo
	lineageTag: 1503b3c4-385a-4ebf-8a5c-275b345a6c62

	column DiaPeriodo
		dataType: int64
		lineageTag: 0dd7ee1a-eb88-4fb6-8aaf-6c339d13cfd2
		summarizeBy: none
		sourceColumn: DiaPeriodo

	column FechaB26
		dataType: dateTime
		formatString: dd-MMM
		lineageTag: 3f680bf6-971e-4a8f-9f5e-abbb4502b8d5
		summarizeBy: none
		sourceColumn: FechaB26

		annotation UnderlyingDateTimeDataType = Date

	column EtiquetaDia
		dataType: string
		lineageTag: f96bc1d9-3749-4dec-8f5e-2ad8faf4fb58
		summarizeBy: none
		sourceColumn: EtiquetaDia
		sortByColumn: DiaPeriodo

	partition DimDiaPeriodo = m
		mode: import
		source =
				let
				    InicioB26 = #date(2026,5,1),
				    T = Table.FromList({1..260}, Splitter.SplitByNothing(), {"DiaPeriodo"}, null, ExtraValues.Error),
				    Types = Table.TransformColumnTypes(T, {{"DiaPeriodo", Int64.Type}}),
				    AddFecha = Table.AddColumn(Types, "FechaB26", each Date.AddDays(InicioB26, [DiaPeriodo]-1), type date),
				    AddEtiqueta = Table.AddColumn(AddFecha, "EtiquetaDia", each Date.ToText([FechaB26], "dd-MMM", "es-ES"), type text)
				in
				    AddEtiqueta

