table DimPeriodo
	lineageTag: 698153f0-7c0b-4b78-b505-d3e464dc0a1f

	column Periodo
		dataType: string
		isKey
		lineageTag: c1383c13-4be9-4627-83a1-138a8ed9ca87
		summarizeBy: none
		sourceColumn: Periodo

	column Ciclo
		dataType: string
		lineageTag: 813575a7-beef-4a38-8ac2-011d4df461e1
		summarizeBy: none
		sourceColumn: Ciclo

	column Anio
		dataType: int64
		lineageTag: b528c0a7-a1b7-4d22-8b32-e8dc6ffdec47
		summarizeBy: none
		sourceColumn: Anio

	column FechaInicio
		dataType: dateTime
		formatString: Short Date
		lineageTag: d43f991b-3242-4a0f-bc78-ce1b65fae637
		summarizeBy: none
		sourceColumn: FechaInicio

		annotation UnderlyingDateTimeDataType = Date

	column FechaFin
		dataType: dateTime
		formatString: Short Date
		lineageTag: eb92aae2-f9ac-4c51-9d80-d48b67ad5295
		summarizeBy: none
		sourceColumn: FechaFin

		annotation UnderlyingDateTimeDataType = Date

	column Orden
		dataType: int64
		lineageTag: 7cce197e-5217-4ce7-982f-40ca9ac56331
		summarizeBy: none
		sourceColumn: Orden

	column EsPeriodoActivo
		dataType: boolean
		lineageTag: d257a230-5891-4e9d-b942-3edd895afdbe
		summarizeBy: none
		sourceColumn: EsPeriodoActivo

	column FechaFinFiltro
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4b39bb0f-64a5-480e-b345-1383bf266b12
		summarizeBy: none
		sourceColumn: FechaFinFiltro

		annotation UnderlyingDateTimeDataType = Date

	column OrigenFechaFin
		dataType: string
		lineageTag: b2afb06c-56af-438b-afe6-ba294cb365b4
		summarizeBy: none
		sourceColumn: OrigenFechaFin

	column FechaInicioGrado
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b5c7e41-2026-1006-0010-000000000001
		summarizeBy: none
		sourceColumn: FechaInicioGrado

		annotation UnderlyingDateTimeDataType = Date

	column FechaFinGrado
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b5c7e41-2026-1006-0010-000000000002
		summarizeBy: none
		sourceColumn: FechaFinGrado

		annotation UnderlyingDateTimeDataType = Date

	column FechaInicioPosgrado
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b5c7e41-2026-1006-0010-000000000003
		summarizeBy: none
		sourceColumn: FechaInicioPosgrado

		annotation UnderlyingDateTimeDataType = Date

	column FechaFinPosgrado
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b5c7e41-2026-1006-0010-000000000004
		summarizeBy: none
		sourceColumn: FechaFinPosgrado

		annotation UnderlyingDateTimeDataType = Date

	partition DimPeriodo = m
		mode: import
		source =
				let
				    Today = Date.From(DateTime.LocalNow()),
				    Files0 = FxSharePointAdmisionesFiles(),
				    Files = Table.Sort(
				        Table.SelectRows(Files0, each
				            Text.Contains(Text.Lower([Folder Path]), "/general/paneles/admisiones/actual/") and
				            Text.Lower([Name]) = "metasbase.xlsx" and
				            not Text.StartsWith([Name], "~$")
				        ),
				        {{"Date modified", Order.Descending}}
				    ),
				    Latest = if Table.RowCount(Files)=0 then error "No se encontro MetasBase.xlsx." else Files{0},
				    Raw = FxReadNamedSheet(Latest[Content], "Tipo"),
				    Tipo0 = Table.SelectColumns(Raw,{"Tipo","Fecha Inicio","Fecha Fin"},MissingField.Error),
				    Tipo = Table.TransformColumns(Tipo0,{
				        {"Tipo", each Text.Upper(FxCleanText(_)), type text},
				        {"Fecha Inicio", each try Date.From(_) otherwise try Date.FromText(Text.From(_),[Culture="en-US"]) otherwise try Date.FromText(Text.From(_),[Culture="es-EC"]) otherwise null, type date},
				        {"Fecha Fin", each try Date.From(_) otherwise try Date.FromText(Text.From(_),[Culture="en-US"]) otherwise try Date.FromText(Text.From(_),[Culture="es-EC"]) otherwise null, type date}
				    }),
				    FilaGrado = Table.SelectRows(Tipo, each [Tipo] = "GRADO"),
				    FilaPosgrado = Table.SelectRows(Tipo, each [Tipo] = "POSGRADO"),
				    FilaB26 = Table.SelectRows(Tipo, each [Tipo] = "B26"),
				    InicioGOrigen = FilaGrado{0}[Fecha Inicio],
				    FinGOrigen = FilaGrado{0}[Fecha Fin],
				    InicioPOrigen = FilaPosgrado{0}[Fecha Inicio],
				    FinPOrigen = FilaPosgrado{0}[Fecha Fin],
				    InicioB26Origen = FilaB26{0}[Fecha Inicio],
				    FinB26Origen = FilaB26{0}[Fecha Fin],
				    InicioG = List.First(List.RemoveNulls({InicioGOrigen,#date(2026,5,4)})),
				    FinG = List.First(List.RemoveNulls({FinGOrigen,#date(2026,10,27)})),
				    InicioP = List.First(List.RemoveNulls({InicioPOrigen,#date(2026,5,4)})),
				    FinP = List.First(List.RemoveNulls({FinPOrigen,#date(2026,11,20)})),
				    InicioB26 = List.First(List.RemoveNulls({InicioB26Origen,#date(2026,5,4)})),
				    FinB26 = List.First(List.RemoveNulls({FinB26Origen,#date(2026,11,30)})),
				    Base0 = Table.FromRecords({
				        [Periodo="B25",Ciclo="B",Anio=2025,FechaInicio=#date(2025,5,1),FechaFin=#date(2025,10,31),FechaInicioGrado=null,FechaFinGrado=null,FechaInicioPosgrado=null,FechaFinPosgrado=null,Orden=20252,OrigenFechaFin="CIERRE_B25"],
				        [Periodo="B26",Ciclo="B",Anio=2026,FechaInicio=#date(2026,5,4),FechaFin=#date(2026,11,30),FechaInicioGrado=#date(2026,5,4),FechaFinGrado=#date(2026,10,27),FechaInicioPosgrado=#date(2026,5,4),FechaFinPosgrado=#date(2026,11,20),Orden=20262,OrigenFechaFin="METASBASE_TIPO_FALLBACK"]
				    }),
				    Base = Table.TransformColumnTypes(Base0,{
				        {"Periodo",type text},{"Ciclo",type text},{"Anio",Int64.Type},{"FechaInicio",type date},{"FechaFin",type date},
				        {"FechaInicioGrado",type date},{"FechaFinGrado",type date},{"FechaInicioPosgrado",type date},{"FechaFinPosgrado",type date},
				        {"Orden",Int64.Type},{"OrigenFechaFin",type text}
				    }),
				    AddActive = Table.AddColumn(Base,"EsPeriodoActivo", each Today >= [FechaInicio] and Today <= [FechaFin], type logical),
				    AddCut = Table.AddColumn(AddActive,"FechaFinFiltro", each if [EsPeriodoActivo] then Today else [FechaFin], type date)
				in
				    AddCut

