table FactMetaMatriz
	lineageTag: 0a8a36dd-4d5f-4476-b25b-202609290001

	column CarreraVisual
		dataType: string
		lineageTag: 0a8a36dd-4d5f-4476-b25b-202609290002
		sourceColumn: CarreraVisual

	column Sede
		dataType: string
		lineageTag: 0a8a36dd-4d5f-4476-b25b-202609290003
		sourceColumn: Sede

	column Modalidad
		dataType: string
		lineageTag: 0a8a36dd-4d5f-4476-b25b-202609290004
		sourceColumn: Modalidad

	column Meta
		dataType: double
		formatString: #,0
		lineageTag: 0a8a36dd-4d5f-4476-b25b-202609290005
		sourceColumn: Meta

	column OfertaB26
		dataType: string
		lineageTag: 0a8a36dd-4d5f-4476-b25b-202609290006
		sourceColumn: OfertaB26

	partition FactMetaMatriz = m
		mode: import
		source =
				let
				    Metas0 = FxLoadMetas(),
				    Keep = Table.SelectColumns(Metas0,{"Carrera","Sede","Modalidad","Meta","Oferta B26"},MissingField.UseNull),
				    AddVisualNorm = Table.AddColumn(Keep,"CarreraVisualNorm",each FxNormalizeName([Carrera]),type text),
				    Catalog = FxLoadCarreraCatalog(),
				    Merge = Table.NestedJoin(AddVisualNorm,{"CarreraVisualNorm"},Catalog,{"CarreraVisualNorm"},"Cat",JoinKind.LeftOuter),
				    Expand = Table.ExpandTableColumn(Merge,"Cat",{"CarreraVisual"},{"CarreraVisualCatalog"}),
				    AddVisual = Table.AddColumn(Expand,"CarreraVisual",each if [CarreraVisualCatalog]<>null then [CarreraVisualCatalog] else [Carrera],type nullable text),
				    Valid = Table.SelectRows(AddVisual,each [CarreraVisual]<>null and [Meta]<>null),
				    Ren = Table.RenameColumns(Valid,{{"Oferta B26","OfertaB26"}},MissingField.Ignore),
				    Result = Table.SelectColumns(Ren,{"CarreraVisual","Sede","Modalidad","Meta","OfertaB26"},MissingField.UseNull)
				in
				    Result

