table FactB26
	column RegistroId
		dataType: int64
		formatString: 0
		sourceColumn: RegistroId

	column Periodo
		dataType: string
		sourceColumn: Periodo

	column Sede
		dataType: string
		sourceColumn: Sede

	column Carrera
		dataType: string
		sourceColumn: Carrera

	column CarreraKey
		dataType: string
		sourceColumn: CarreraKey

	column Modalidad
		dataType: string
		sourceColumn: Modalidad

	column FechaMatricula
		dataType: dateTime
		formatString: Short Date
		sourceColumn: FechaMatricula

	column DiaPeriodo
		dataType: int64
		formatString: 0
		sourceColumn: DiaPeriodo

	column TipoPrograma
		dataType: string
		sourceColumn: TipoPrograma

	column TieneMeta
		dataType: boolean
		sourceColumn: TieneMeta

	column EsFormalizado
		dataType: boolean
		sourceColumn: EsFormalizado

	column EnPeriodo
		dataType: boolean
		sourceColumn: EnPeriodo

	partition FactB26 = m
		mode: import
		source =
				let
				    Wb = Excel.Workbook(File.Contents(SourceFolder & "\615.xlsx"), null, true),
				    Raw = Wb{[Item="reporte",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Raw,[PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted,{"Periodo","Sede","CARRERA","MODALIDAD","IDENTIFICACION","FECHA MATRICULA","FORMALIZADO","HOMOLOGA","MATRICULA EN PRIMERO"},MissingField.UseNull),
				    Renamed = Table.RenameColumns(Selected,{{"CARRERA","Carrera"},{"MODALIDAD","Modalidad"},{"IDENTIFICACION","Identificacion"},{"FECHA MATRICULA","FechaMatricula"},{"FORMALIZADO","Formalizado"},{"HOMOLOGA","Homologa"},{"MATRICULA EN PRIMERO","MatriculaPrimero"}}),
				    Clean = Table.TransformColumns(Renamed,{{"Periodo",FxNormalize,type text},{"Sede",FxNormalize,type text},{"Carrera",FxCleanText,type text},{"Modalidad",FxNormalize,type text},{"Identificacion",FxCleanText,type text},{"Formalizado",FxNormalize,type text},{"Homologa",FxNormalize,type text},{"MatriculaPrimero",FxNormalize,type text},{"FechaMatricula",each try Date.From(_) otherwise null,type date}}),
				    Candidates = Table.SelectRows(Clean,each [Periodo]="B26" and [Homologa]="NO" and [MatriculaPrimero]="SI"),
				    AddKey = Table.AddColumn(Candidates,"CarreraKey",each FxCareerKey([Carrera]),type text),
				    AddType = Table.AddColumn(AddKey,"TipoPrograma",each FxTipoPrograma([CarreraKey]),type text),
				    AddTarget = Table.AddColumn(AddType,"TieneMeta",each List.Contains(FactMetasCarrera[CarreraKey],[CarreraKey]),type logical),
				    AddFormal = Table.AddColumn(AddTarget,"EsFormalizado",each [Formalizado]="SI",type logical),
				    AddPeriod = Table.AddColumn(AddFormal,"EnPeriodo",each [FechaMatricula]<>null and [FechaMatricula]>=#date(2026,5,1) and [FechaMatricula]<=#date(2026,9,30),type logical),
				    AddDay = Table.AddColumn(AddPeriod,"DiaPeriodo",each if [EnPeriodo] then Duration.Days([FechaMatricula]-#date(2026,5,1))+1 else null,Int64.Type),
				    AddId = Table.AddIndexColumn(AddDay,"RegistroId",1,1,Int64.Type),
				    Result = Table.RemoveColumns(AddId,{"Identificacion","Homologa","MatriculaPrimero","Formalizado"})
				in
				    Result
